### ISSUE TITLE
Exes on windows cant find UDP Packets

### ISSUE THREAD

**Issue by Kitick** [Kitick/Infinite-Flight-Copilot#3]
Windows ran on the exes cant pick up packets where through node they can.
Last test on linux did work however. Mac untested

**Comment by ghost** [comment]
Possible issue is a file dependency issue that is not being compiled into the exe.

**Comment by Kitick** [comment]
Issue went away, then came back in recent push. Unsure of what is causing this.

**Comment by Kitick** [comment]
Issue seams to be the node version. Compiling to node16 fixed the issue.
