### ISSUE TITLE
State Cache Feature

### ISSUE THREAD

**Issue by ghost** [Kitick/Infinite-Flight-Copilot#9]
Considering functions are updated on their own independent loops, sometimes the same state is requested not milliseconds after it was already requested. Causing a lot of unnecessary network traffic.

Possible solution is to cache values for a given amount of time, possibly based on update time, in-order for states to be requested once and used multiple times. Possible issue is a added delay of current information, and could cause functions to have a noticeable response issue.

Another solution is to update the loops so that they are all active at the same time, witch would allow the system to cache the request natively server-side. One issue with this is causing lag spikes with having all logic happen at the same time rather than spread out.

Will most likely go with a hybrid approach of caching values up to a set about of time, and pushing all updates to be spread-out but still within that window. Further consideration needed.

**Comment by Kitick** [comment]
Fully added!
